name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building.
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Downloading & Installing Essentials
        shell: powershell
        run: |
          curl.exe -L "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -o Downloads.bat
          if (!(Test-Path Downloads.bat)) {
            Write-Error "Downloads.bat not found"
            exit 1
          }
          cmd /c Downloads.bat

      - name: Show Website
        shell: cmd
        run: |
          call show.bat
